[package]
name = "chip8-ii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
winit = { version = "0.30.1", features = ["rwh_05"]}
pixels = "0.13.0"
